### ISSUE TITLE
Send commands from client to server over TCP

### ISSUE THREAD

**Issue by thobson88** [alan-turing-institute/bluesky#1]
Add script(s) demonstrating client -> server communication.

**Comment by Ruairidh** [comment]
I have added a couple of scripts to branch [ruairidh_hacking](https://github.com/alan-turing-institute/bluesky/tree/ruairidh_hacking) to demonstrate this. They can interact with a running BlueSky simulation.

- CommandTest.py contains a barebones implementation of some bluesky client objects to send data. By default it sends the `IC IC` command, which reloads the currently running simulation.

- CommandCli.py contains a subclass of the bluesky client object, and overrides the default `receive` method (just so we can print out data for now). When run you can select either `listen` or `command` mode. Listen mode will print any messages received to console, and command mode will allow you to pass commands to the simulation as if through the GUI. Using this I have been able to create aircraft which appear in the simulation.

**Comment by Ruairidh** [comment]
See https://github.com/alan-turing-institute/bluesky/blob/ruairidh_hacking/turing/scripts/Readme.md#commandtestpy
