### ISSUE TITLE
Create skeleton web server to interact with Bluesky client/server

### ISSUE THREAD

**Issue by evelinag** [alan-turing-institute/bluesky#12]
Using either Flask or Flask-admin, based on the outcome of issue #7.

Also, decide where to put the code
- this repo
- separate repo as a github submodule

**Comment by evelinag** [comment]
I created a repo for the server, [bluebird](https://github.com/alan-turing-institute/bluebird). The dependency on Bluesky is going to be fairly static so git submodules should work for this.

**Comment by Ruairidh** [comment]
Initial skeleton added to bluebird repo
