### ISSUE TITLE
Receive responses from the server over TCP

### ISSUE THREAD

**Issue by thobson88** [alan-turing-institute/bluesky#2]
Add script(s) demonstrating two-way client-server communication.

**Comment by Ruairidh** [comment]
Added script to create an aircraft and continually poll for its location. See da27f35fcdbf040bc3bf8b147dea0559426ba1ed

**Comment by Ruairidh** [comment]
See https://github.com/alan-turing-institute/bluesky/blob/ruairidh_hacking/turing/scripts/Readme.md#getaircraftlocpy
