### ISSUE TITLE
pip or pip3 in install.sh

### ISSUE THREAD

**Issue by kasra-hosseini** [alan-turing-institute/bluesky#21]
https://github.com/alan-turing-institute/bluesky/blob/b413c9defdfa461cb0fcf23c2c5da3fe3b165f81/install.sh#L11-L17

I had to change all `pip3` to `pip` in `install.sh` to make it work. Maybe we can replace lines 11-17 of install.sh (above) with (I am not sure what is the best way to do this in bash):

```bash
# Check for pip3.
if command -v pip3 &>/dev/null; then
    printf "Found pip3\n"
    pip_path="$(command -v pip3)"
    pip_cmd="${pip_path}"
# Check for pip.
elif command -v pip &>/dev/null; then
    printf "Found pip\n"
    pip_path="$(command -v pip)"
    pip_cmd="${pip_path}"
else
    printf "Please install python3-pip\n"
    exit 1
```

and replace all pip3 in install.sh with `$pip_cmd`, e.g.:

```bash
pip3 install --upgrade virtualenv
# replace with:
$pip_cmd install --upgrade virtualenv
```

**Comment by LiamDeacon-NATS** [comment]
Hi @kasra-hosseini - I'm not sure if this will help, so bare with me! Depending on your python version (and if you're using a virtualenv), you can reliably use the correct version of pip with `python3 -m pip` instead of simply pip (which may or may not be the python 3 version depending on your system...)

**Comment by kasra-hosseini** [comment]
@LiamDeacon-NATS Thanks. That is very helpful!

**Comment by LiamDeacon-NATS** [comment]
I found the `command` check didn't work reliably for me in my mangled WSL environment, so I changed it to use a `wc -l` style check instead in #34

**Comment by LiamDeacon-NATS** [comment]
@thobson88 / @rkm - Does #34 address this issue?
