### ISSUE TITLE
Interact with a simple scenario over TCP

### ISSUE THREAD

**Issue by thobson88** [alan-turing-institute/bluesky#8]
Start the simple scenario (#3) and interact with it over TCP:
 - [x] Send the scenario to the simulator and start it running
 - [x] Get info about a particular aircraft
 - [x] Send a command to instruct the aircraft to climb to a particular altitude
 - [x] Get info about the same aircraft and confirm the climb command was received

**Comment by Ruairidh** [comment]
Added a very rough script for this - will update it to use a basic scenario so the effects of the commands issued are clearer.

**Comment by Ruairidh** [comment]
See https://github.com/alan-turing-institute/bluesky/blob/ruairidh_hacking/turing/scripts/Readme.md#scenariointeractionpy
